### ISSUE TITLE
Question about testing and deployment

### ISSUE THREAD

**Issue by PatrickAlphaC** [freitasgouvea/deed-angular#1]
Hi Guys! I just wanted to ask how you did the testing and migrations, specifically around funding ropsten contracts.

Did you manually fund them with LINK after each deployment?

**Comment by MatheusDaros** [comment]
Yep. We included a function in the app for users to buy Link using DAI and/or ETH through Uniswap, but the most practical way is to simply request the Link through a faucet and send it to the contracts.

For the unit tests, I used the Mock module of buidler to abstract this part.

**Comment by MatheusDaros** [comment]
Please note that we have migrate the project to: https://github.com/uproot-dev/uproot-trustless-app

**Comment by PatrickAlphaC** [comment]
Got it, thanks for the heads up! Very cool
